trigger:
  batch: true
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

schedules:
  - cron: '0 0 * * 0'
    displayName: Weekly build
    branches:
      include:
        - main
    always: true

resources:
  repositories:
    - repository: templates
      type: github
      name: osisoft/OSI-Samples
      endpoint: osisoft/OSI-Samples

variables:
  - template: '/miscellaneous/build_templates/variables.yml@templates'
  - name: analysisProject
    value: Lib_Python

jobs:
  - job: Analysis
    pool:
      name: 00-OSIManaged-Containers
      demands: Agent.OS -equals Windows_NT
    steps:
      - script: |
          echo Install tools
          call pip install wheel
          call pip install twine
          echo Build library
          call python setup.py sdist bdist_wheel
          echo Complete
        displayName: 'Build'

      - template: '/miscellaneous/build_templates/analysis.yml@templates'
